# Generated by Django 3.2 on 2021-05-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resgistrolab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='año',
            new_name='ano',
        ),
    ]
