# Generated by Django 3.2 on 2021-05-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resgistrolab', '0002_rename_año_curso_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='ano',
        ),
    ]
