# Generated by Django 3.2 on 2021-05-05 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resgistrolab', '0003_remove_curso_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='semestre',
        ),
    ]
